name: CI
on: [push, pull_request]

jobs:

  windows-msvc:
    strategy:
      matrix:
        platform: [x64]
    runs-on: windows-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.3.1
      - name: Build
        run: |
          MSBuild.exe vcproj/mp4fpsmod.sln /m /p:Configuration=Release /p:Platform=${{ matrix.platform }}
      - name: Upload mp4fpsmod Artifact
        uses: actions/upload-artifact@v2
        with:
          name: mp4fpsmod_win_x64
          path: vcproj/x64/Release/mp4fpsmod
